// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectSchool_API.Data;

namespace ProjectSchool_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210920012343_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("ProjectSchool_API.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Birth")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .HasColumnType("longtext");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birth = "22/12/2002",
                            Name = "John",
                            Surname = "Doe",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            Birth = "12/06/1992",
                            Name = "Jane",
                            Surname = "Doe",
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 3,
                            Birth = "01/03/2000",
                            Name = "Gabriel",
                            Surname = "Doe",
                            TeacherId = 3
                        });
                });

            modelBuilder.Entity("ProjectSchool_API.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bruce T ",
                            Surname = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Julia T ",
                            Surname = "Doe"
                        },
                        new
                        {
                            Id = 3,
                            Name = "John T ",
                            Surname = "Doe"
                        });
                });

            modelBuilder.Entity("ProjectSchool_API.Models.Student", b =>
                {
                    b.HasOne("ProjectSchool_API.Models.Teacher", "Teacher")
                        .WithMany("Students")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ProjectSchool_API.Models.Teacher", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
